language: c
os: linux
install:
 - INSTALL_HERE="$(pwd)/libs"
 - LIBS_I="$INSTALL_HERE""/includes"
 - LIBS_L="$INSTALL_HERE""/objects"
 - . .travis/install_cmocka.sh
 - ls -R $INSTALL_HERE
 - . .travis/install_42FileChecker.sh
script:
 - make
 - make unit-tests < ./sources/get_next_line.c
 - make clean-gnl
 - bash ~/42FileChecker/42FileChecker.sh --project "gnl" --path "./gnl" --no-norminette
