language: c

os:
 - linux

install:
 - INSTALL_HERE="$(pwd)/libs"
 - LIBS_I="$INSTALL_HERE""/includes"
 - LIBS_L="$INSTALL_HERE""/objects"
 - . .travis/install_cmocka.sh
 - ls -R $INSTALL_HERE
 - . .travis/install_42FileChecker.sh

before_script :
 - make libft

script:
 - make
 - make unit-tests
 - make project
 - bash ~/42FileChecker/42FileChecker.sh --project "gnl" --path "$(pwd)/project" --no-norminette
 - cat ~/42FileChecker/.my*

